### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [Milindpatel/MEAN-Website#1]
Hi,

it seems you have accidentally added `mongose` but this is not the real package on npmjs.

https://github.com/Milindpatel/MEAN-Website/blob/master/package.json#L29

See https://npmjs.org/mongose

You might want to remove it using `npm uninstall mongose`.

**Comment by Milindpatel** [comment]
Hello Daniel,

I have removed it from package.json file.

Thanks,
Milind Patel
